ConvertAnnotationsToCSV:
  description: >
    Transform {JSON} annotation data into CSV format with proper boolean values
  expected_output: >
    The output will be a csv in the following format with only these headers and can have bool values only:
    standing,hands_visible,indoor,physicaltouch
    true/false,true/false,true/false,true/false

  agent: AnnotationConverterAgent

ValidateCSVStructure:
  description: >
    Verify CSV format and boolean values consistency.
  expected_output: >
    Validation report with any discrepancies found
    
  agent: DataQualityAgent

GenerateFinalCSV:
  description: Produce final CSV file with validated data
  expected_output: >
    Properly formatted CSV file ready for analysis

  agent: AnnotationConverterAgent