ConvertAnnotationsToCSV:
  description: >
    Transform {JSON} annotation data into CSV format with proper boolean values
  expected_output: >
    The output will be a csv in the following format with only these headers and can have bool values only:
    standing,hands_visible,indoor,physicaltouch
    true/false,true/false,true/false,true/false

  agent: AnnotationConverterAgent
